name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/logo.png

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # <--- AÑADE ESTA LÍNEA
    sdk: flutter         # <--- AÑADE ESTA LÍNEA
  http: ^1.2.0
  flutter_secure_storage: ^10.0.0
  cupertino_icons: ^1.0.2
  device_info_plus: ^12.3.0
  provider: ^6.1.5+1
  intl: ^0.20.2
